# Generated by Django 4.1.7 on 2023-05-08 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("starting_bid", models.IntegerField()),
                ("description", models.TextField()),
                ("imageUrl", models.CharField(blank=True, max_length=512, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "bought",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watchlist",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="wl",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
