# Generated by Django 4.1.7 on 2023-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="active",
            field=models.CharField(max_length=64),
        ),
    ]
