# Generated by Django 4.1.7 on 2023-05-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listing_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="active",
            field=models.CharField(
                blank=True, default="active", max_length=64, null=True
            ),
        ),
    ]
