# Generated by Django 4.1.7 on 2023-05-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_listing_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
